#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : funcparserlib
Version  : 0.3.6
Release  : 8
URL      : http://pypi.debian.net/funcparserlib/funcparserlib-0.3.6.tar.gz
Source0  : http://pypi.debian.net/funcparserlib/funcparserlib-0.3.6.tar.gz
Summary  : Recursive descent parsing library based on functional combinators
Group    : Development/Tools
License  : MIT
Requires: funcparserlib-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
funcparserlib
=============
A recurisve descent parsing library based on functional combinators.

%package python
Summary: python components for the funcparserlib package.
Group: Default

%description python
python components for the funcparserlib package.


%prep
%setup -q -n funcparserlib-0.3.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1503089504
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1503089504
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
/usr/lib/python3*/*
