#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : funcparserlib
Version  : 0.3.6
Release  : 1
URL      : https://pypi.python.org/packages/source/f/funcparserlib/funcparserlib-0.3.6.tar.gz
Source0  : https://pypi.python.org/packages/source/f/funcparserlib/funcparserlib-0.3.6.tar.gz
Summary  : Recursive descent parsing library based on functional combinators
Group    : Development/Tools
License  : MIT
Requires: funcparserlib-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : setuptools

%description
funcparserlib
=============
A recurisve descent parsing library based on functional combinators.

%package python
Summary: python components for the funcparserlib package.
Group: Default

%description python
python components for the funcparserlib package.


%prep
%setup -q -n funcparserlib-0.3.6

%build
python2 setup.py build -b py2

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
